# Site settings
author: Carissa Sarreal
title: MindSpace
header-img: img/home-bg.png
email: carissa.sarreal@gmail.com
copyright_name: Carissa Sarreal
description: > # this means to ignore newlines until "baseurl:"
  where the wild thoughts grow
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  imcarissa

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
